// Generated by CoffeeScript 1.6.2
var boots, create_file, events, fs, path, rain, _ref;

events = require("events");

exports.rain = new events.EventEmitter;

_ref = require("rain-boots"), rain = _ref.rain, boots = _ref.boots;

fs = require("fs");

path = require("path");

create_file = function(base_path, data) {
  var file_path, keys;

  if ((typeof data) === "string") {
    file_path = path.join(base_path, data);
    return fs.writeFileSync(file_path, "");
  } else {
    keys = Object.keys(data);
    return keys.forEach(function(key) {
      var new_path, value;

      value = data[key];
      new_path = path.join(base_path, key);
      fs.mkdirSync(new_path);
      return create_file(new_path, value);
    });
  }
};

exports.rain.on("create", function(tree, base_path) {
  base_path = base_path || ".";
  create_file(base_path, tree);
  return exports.rain.emit("created", tree);
});

exports.rain.on("erase", function(tree, base_path) {
  var keys;

  keys = Object.keys(tree);
  base_path = base_path || "";
  keys.forEach(function(key) {
    var path_name;

    path_name = path.join(base_path, key);
    return boots.erase_path(path_name);
  });
  return exports.rain.emit("erased", tree);
});
