// Generated by CoffeeScript 1.6.2
var create_file, events, fs, path, ring;

events = require("events");

exports.ring = ring = new events.EventEmitter;

fs = require("fs");

path = require("path");

create_file = function(base_path, data) {
  var file_path, keys;

  if ((typeof data) === "string") {
    file_path = path.join(base_path, data);
    return fs.writeFile(file_path, "");
  } else {
    keys = Object.keys(data);
    console.log(keys);
    return keys.forEach(function(key) {
      var new_path, value;

      value = data[key];
      new_path = path.join(base_path, key);
      return fs.mkdir(new_path, function() {
        return create_file(new_path, value);
      });
    });
  }
};

ring.on("create", function(tree, base_path) {
  base_path = base_path || ".";
  return create_file(base_path, tree);
});
